name: fastoma-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - omamer
  - mafft
  - fasttree
  - nextflow
  - papermill
  - seaborn
  - matplotlib
  - pyparsing
  - networkx
  - jupyter
  - pip
  - pip:
    - .[report]
